### ISSUE TITLE
Sun Source is not being copied

### ISSUE THREAD

**Issue by ziplock9000** [pschraut/UnityCopyLightingSettings#1]
I've just tested the new 1.4.0 version and Lighting->Environment->Sun Source is not being copied.
Unity 2020.2.0b14.3668

**Comment by pschraut** [comment]
Yes, this is on purpose. The reason why "Sun Source" is not copied is because Unity does not support cross scene references. 

If you have two scenes, _MainScene_ and _AdditionalScene_ and you add a reference from a light in MainScene to the AdditionalScene "Sun Source", Unity outputs this warning:
> Cross scene references are not supported: 'RenderSettings' in scene AdditionalScene has an invalid reference to 'Directional Light' in scene MainScene. This reference will not be saved in the scene.

**Comment by ziplock9000** [comment]
Can make so that it binds up any light with the same name and maybe make that an option? 99/100 the name will be the same and unique for people who use this too to mass-produce say level scenes.

**Comment by pschraut** [comment]
Please take a look at 1.5.0, the "Sun Source" setting is "copied" now too. 

"Sun Source" is a reference to a Light Component in the scene, but Unity does not support cross scene references. Therefore the tool does not copy&paste the reference, but it looks for a Light with the same name (upper/lower-case ignored) in the target scene. It looks first for active lights, then inactive lights.

If a Light with the same name exists in the target scene and there is currently no "Sun Source" assigned, then the tool sets it to the Light found in that scene.

Does this work for you?

**Comment by ziplock9000** [comment]
Works well thanks!. 

Although I'm not sure the version number has been updated everywhere. https://i.imgur.com/RONdrQv.png
